### ISSUE TITLE
crash when downloading daemon timeouts

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#751]
## reproduce
- remove data directory (`/home/user/.config/Particl Desktop/`)
- disconnect internet
- launch wallet
- connection fails
- 20 js popups + crash

**Comment by EagleEye25** [comment]
is this the desired reproduced output:
![daemon error](https://user-images.githubusercontent.com/28861857/35330802-7e60fec0-010d-11e8-8b4a-d745499fc1ba.gif)
i only got one js popup

**Comment by kewde** [comment]
```
[14:11:01.281] [info] Initializing...
[14:11:01.281] [info] Resolving path to client binary ...
[14:11:01.281] [debug] Platform: linux
[14:11:01.282] [info] Client binary path: /home/user/.config/Particl Desktop/particld/unpacked/particld
[14:11:01.282] [info] Checking for new client binaries config from: https://raw.githubusercontent.com/particl/particl-desktop/dev/modules/clientBinaries/clientBinaries.json
[14:11:01.283] [debug] Status: loadConfig - Fetching remote client config
[14:11:01.309] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie
[14:11:01.311] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie
[14:11:08.316] [warn] Error fetching client binaries config from repo Error: Request timed out
    at timeoutFn (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/node_modules/got/index.js:288:53)
    at asPromise (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/node_modules/got/index.js:358:18)
    at got (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/node_modules/got/index.js:588:10)
    at DaemonManager._checkForNewConfig (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/modules/daemon/daemonManager.js:69:12)
    at DaemonManager.init (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/modules/daemon/daemonManager.js:43:17)
    at daemon.check.then.catch (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/modules/init.js:18:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

[14:11:08.445] [info] No config for the ClientBinariesManager could be loaded, using local clientBinaries.json.
[14:11:08.452] [error] Error: Cannot find module './clientBinaries.json'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at got.then.catch.then.then (/home/user/Downloads/particl-desktop/particl-desktop-1.1.0-RC3-linux-x64/resources/app.asar/modules/daemon/daemonManager.js:206:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

[14:11:08.455] [debug] Status: error - Cannot find module './clientBinaries.json'
[14:11:08.457] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie
[14:11:08.458] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie
[14:11:08.459] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie
[14:11:08.610] [info] starting daemon /home/user/.config/Particl Desktop/particld/unpacked/particld -testnet,-printtoconsole 
[14:11:24.144] [debug] could not find cookie file! path: /home/user/.particl/testnet/.cookie

```

^just for the record, that's the output log for this bug.

**Comment by kewde** [comment]
Need to try { } catch { } it..

**Comment by HenkSwardt** [comment]
Please confirm it this could relate to #756

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/particl-desktop/pull/763

**Comment by kewde** [comment]
@anandsinghparihar we only close issue if the PR has been merged.

**Comment by HenkSwardt** [comment]
Can this issue please be merged?
